// <auto-generated />
using System;
using CoachTraining.Infra.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoachTraining.Infra.Persistence.Migrations
{
    [DbContext(typeof(CoachTrainingDbContext))]
    partial class CoachTrainingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoachTraining.Infra.Persistence.Models.AtletaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("NivelEsportivo")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ObservacoesClinicas")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("atletas", (string)null);
                });

            modelBuilder.Entity("CoachTraining.Infra.Persistence.Models.ProfessorModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("professores", (string)null);
                });

            modelBuilder.Entity("CoachTraining.Infra.Persistence.Models.ProvaAlvoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AtletaId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DataProva")
                        .HasColumnType("date");

                    b.Property<double>("DistanciaKm")
                        .HasColumnType("double precision");

                    b.Property<string>("Objetivo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId")
                        .IsUnique();

                    b.ToTable("provas_alvo", (string)null);
                });

            modelBuilder.Entity("CoachTraining.Infra.Persistence.Models.SessaoDeTreinoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AtletaId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<double>("DistanciaKm")
                        .HasColumnType("double precision");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer");

                    b.Property<int>("Rpe")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId");

                    b.HasIndex("Data");

                    b.HasIndex("AtletaId", "Data");

                    b.ToTable("sessoes_treino", (string)null);
                });

            modelBuilder.Entity("CoachTraining.Infra.Persistence.Models.AtletaModel", b =>
                {
                    b.HasOne("CoachTraining.Infra.Persistence.Models.ProfessorModel", "Professor")
                        .WithMany("Atletas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("CoachTraining.Infra.Persistence.Models.ProvaAlvoModel", b =>
                {
                    b.HasOne("CoachTraining.Infra.Persistence.Models.AtletaModel", "Atleta")
                        .WithOne("ProvaAlvo")
                        .HasForeignKey("CoachTraining.Infra.Persistence.Models.ProvaAlvoModel", "AtletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atleta");
                });

            modelBuilder.Entity("CoachTraining.Infra.Persistence.Models.SessaoDeTreinoModel", b =>
                {
                    b.HasOne("CoachTraining.Infra.Persistence.Models.AtletaModel", "Atleta")
                        .WithMany("SessoesDeTreino")
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atleta");
                });

            modelBuilder.Entity("CoachTraining.Infra.Persistence.Models.AtletaModel", b =>
                {
                    b.Navigation("ProvaAlvo");

                    b.Navigation("SessoesDeTreino");
                });

            modelBuilder.Entity("CoachTraining.Infra.Persistence.Models.ProfessorModel", b =>
                {
                    b.Navigation("Atletas");
                });
#pragma warning restore 612, 618
        }
    }
}
